# Generated by Django 2.2.5 on 2020-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200106_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='winner',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
