# Generated by Django 2.2.5 on 2020-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playergameinfo_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='winner',
            field=models.BooleanField(null=True),
        ),
    ]
