# Generated by Django 2.2.5 on 2020-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200106_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='try_count',
            field=models.IntegerField(default=0),
        ),
    ]
